language: python
python:
  - "3.6"
  - "3.7"
os:
  - linux
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database sports;' -U postgres
  - psql -c "create user alex with password 'password123';"  -U postgres
  - psql -c "grant all privileges on database sports to alex;" -U postgres
script:
  - pytest
  - bash ./script.sh